[project]
name = "project-legal-doc-analyzer"
version = "0.1.0"
description = "CRAG based Law Assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "boto3>=1.43.40",
    "botocore>=1.43.40",
    "cerebras-cloud-sdk>=1.67.0",
    "chromadb>=1.5.8",
    "email-validator>=2.3.0",
    "faiss-cpu>=1.13.2",
    "fastapi>=0.136.0",
    "jupyter>=1.1.1",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-core>=1.3.0",
    "langchain-google-genai>=4.2.2",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.2.0",
    "langchain-tavily>=0.2.18",
    "langchain-voyageai>=0.4.0",
    "nbconvert>=7.17.1",
    "nltk>=3.9.4",
    "pgvector>=0.4.2",
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.3",
    "pypdf>=6.10.2",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.29",
    "sentence-transformers>=5.5.0",
    "spacy>=3.8.14",
    "sqlalchemy>=2.0.49",
    "supabase>=2.31.0",
    "tavily-python>=0.7.24",
    "uvicorn>=0.45.0",
]
